### ISSUE TITLE
`rand()` is not suitable for DSP code

### ISSUE THREAD

**Issue by x42** [sjaehn/BAngr#1]
https://github.com/sjaehn/BAngr/blob/71f3bc6cc22f312deb4acd327d6e26963e886326/src/Airwindows/XRegion.cpp#L38-L39

see also https://github.com/airwindows/airwindows/issues/28#issuecomment-851516451
and https://github.com/airwindows/airwindows/pull/31

Also note that rand() on windows is only 15 bit

**Comment by sjaehn** [comment]
I know this one. `rand()` is only used within a constructor called by `instantiate()`. Outside the realtime thread. Therefore I don't see this problem here.
